apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand-connect
spec:
  selector:
    matchLabels:
      run: brand-connect
  replicas: 1
  template:
    metadata:
      labels:
        run: brand-connect
    spec:
      containers:
        - name: brand-connect
          image: coinqvest/brand-connect:latest
          env:
            - name: WS_BRANDING_KEY
              value: "demo"

---

apiVersion: v1
kind: Service
metadata:
  name: brand-connect
  labels:
    run: brand-connect
spec:
  selector:
    run: brand-connect
  ports:
    - name: http
      port: 80
      protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brand-connect
spec:
  rules:
    - host: "coinqvest.k8s.sui.li"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brand-connect
                port:
                  number: 80